### ISSUE TITLE
Add outstanding sites from elm-community/builtwithelm

### ISSUE THREAD

**Issue by dwayne** [dwayne/builtwithelm#3]
- https://github.com/elm-community/builtwithelm/pull/194
- https://github.com/elm-community/builtwithelm/pull/195
- ~~https://github.com/elm-community/builtwithelm/pull/196~~ - The website isn't working
- https://github.com/elm-community/builtwithelm/pull/197

**Comment by dwayne** [comment]
@andrewMacmurray, @eimfach, @ceddlyburge your projects have been added. Thank you all so much for your contributions.

- [Seeds Game](https://builtwithelm.co/?q=seeds)
- [CSV Batch Tagger](https://builtwithelm.co/?q=csv%20batch%20tagger)
- [League Tables](https://builtwithelm.co/?q=league%20tables)

@lawsdontapplytopigs Your website isn't working so I couldn't add your project. Please feel free to resubmit once you have it working again.

**Comment by andrewMacmurray** [comment]
That's awesome, thank you @dwayne!

**Comment by eimfach** [comment]
Thank you ! That's great !
