### ISSUE TITLE
some more repos

### ISSUE THREAD

**Issue by brandly** [dwayne/builtwithelm#5]
Hi @dwayne! I saw your repo mentioned on Slack. I've got some repos that are mostly personal experiments. Interested in having them added?
* https://github.com/brandly/elm-slime-volleyball
* https://github.com/brandly/elm-rocket-league
* https://github.com/brandly/elm-dr-mario
* https://github.com/brandly/elm-minesweeper (i think you've got a few of these already lol)

Not mine but this is a pretty cool app:
* https://github.com/erkal/kite

Let me know what you think!

**Comment by dwayne** [comment]
Hi @brandly, thanks for suggesting these apps. I checked them all out and I'd love to have them on the site. There's always room for more minesweeper and yours is well structured in addition to being highly polished graphically. I'd definitely be taking some ideas from these repos. :)

However, please follow the [submission guidelines](https://github.com/dwayne/builtwithelm#submissions) to have them added to the site. It makes maintainence easier if everyone follows the same process.

**Comment by dwayne** [comment]
@brandly I added the apps to the site. Thanks again for suggesting them.
@erkal Thanks for kite.

Ref: https://github.com/dwayne/builtwithelm/commit/c1ca046d4516a1e81b1f44f7d1cbb0268eaaa702

**Comment by brandly** [comment]
Thanks for taking care of it Dwayne!!
